name: Build

on:
  push:
    tags:
      - '*.*.*'
jobs:  
  build:
    runs-on: windows-latest  

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Install .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    
    - name: Install Squirrel CLI
      run: dotnet tool install --global csq --version 3.0.210-g5f9f594
        
    - name: Restore Packages
      run: dotnet restore
    
    - name: Publish
      run: dotnet publish -c Release -o ./bin/Publish
      
    - name: Download Live Version
      run: csq github-down -r ./bin/Squirrel --repoUrl https://github.com/sirdoombox/F1Desktop
        
    - name: Pack Squirrel Release
      run: csq pack -u F1Desktop -v ${{github.ref_name}} -p ./bin/Publish -r ./bin/Squirrel -e F1Desktop.exe -i ./Resources/f1.ico --appIcon ./Resources/f1.ico --releaseNotes ./Resources/Changelogs/${{ github.ref_name }}.MD
      
    - name: Upload Squirrel Release
      run: csq github-up -r ./bin/Squirrel --repoUrl https://github.com/sirdoombox/F1Desktop --token ${{ secrets.GITHUB_TOKEN }} --releaseName "F1 Desktop v${{github.ref_name}}" --publish
