name: Publish and pack with Squirrel

on:
  push:
    tags:
      - '*.*.*'
jobs:  
  build:
    strategy:
      matrix:
        configuration: [Release]
    runs-on: windows-latest  

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Install .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    
    - name: Install Squirrel CLI
      run: dotnet tool install --global csq --version 3.0.170-unstable-ge14820
        
    - name: Restore Packages
      run: dotnet restore
    
    - name: Publish
      run: dotnet publish -c Release -o ./bin/Publish
      
    - name: Download Live Version
      run: csq github-down -r ./bin/Squirrel --repoUrl https://github.com/sirdoombox/F1Desktop
        
    - name: Pack Squirrel Release
      run: csq pack -u F1Desktop -v ${{github.ref_name}} -p ./bin/Publish -r ./bin/Squirrel -e F1Desktop.exe -i ./Resources/f1.ico
      
    - name: Trim RELEASES
      run: (Get-Content bin/Squirrel/RELEASES | Select-Object -Skip 2) | Set-Content bin/Squirrel/RELEASES
        
    - name: Upload Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        release_name: F1 Desktop v${{github.ref_name}}
        file_glob: true
        file: |
          bin/Squirrel/F1Desktop-${{github.ref_name}}-full.nupkg
          bin/Squirrel/F1Desktop-${{github.ref_name}}-delta.nupkg
          bin/Squirrel/F1DesktopSetup.exe
          bin/Squirrel/RELEASES
